schema = 3

[mod]
  [mod."github.com/ebitengine/gomobile"]
    version = "v0.0.0-20241016022004-957bd3215dd8"
    hash = "sha256-F+ajp4WFAm/aFUoftSijJWU1zfyiWxeAgDGB4grfDOo="
  [mod."github.com/ebitengine/hideconsole"]
    version = "v1.0.0"
    hash = "sha256-YeOXzCqLsTJssPGMgp56Fe1YDRd7RIkyHywr7/5rBRs="
  [mod."github.com/ebitengine/purego"]
    version = "v0.8.0"
    hash = "sha256-fM+5HYIKDPLDrvv2f9/WQG0F20+o0+At0AbPQtF2JP0="
  [mod."github.com/hajimehoshi/ebiten/v2"]
    version = "v2.8.9"
    hash = "sha256-CcCtJC7pvAYnUL8N9cOxyKQODQ1KvlQGFv+zG3Kilnk="
  [mod."github.com/jezek/xgb"]
    version = "v1.1.1"
    hash = "sha256-LjbHWx2dzeVUOf3+VYpMZk+mXkxjwRR+v0oH3ZfPEDY="
  [mod."golang.org/x/sync"]
    version = "v0.8.0"
    hash = "sha256-usvF0z7gq1vsX58p4orX+8WHlv52pdXgaueXlwj2Wss="
  [mod."golang.org/x/sys"]
    version = "v0.26.0"
    hash = "sha256-YjklsWNhx4g4TaWRWfFe1TMFKujbqiaNvZ38bfI35fM="
